/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PublisherAdInventoryOrganizer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Publisher;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vaibhavagarwal
 */
public class AdInventoryOrganizerWorkAreaJPanel extends javax.swing.JPanel {
private JPanel container;
private Publisher publisher;
private EcoSystem system;
    /**
     * Creates new form AdInventoryOrganizerWorkAreaJPanel
     */
    public AdInventoryOrganizerWorkAreaJPanel(JPanel container,Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.container=container;
        this.publisher=(Publisher)enterprise;
        this.system=system;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ManageInventoryJButton = new javax.swing.JButton();
        ManageInventoryRevJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -AdInventory Management");

        ManageInventoryJButton.setText("Manage Inventory ");
        ManageInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageInventoryJButtonActionPerformed(evt);
            }
        });

        ManageInventoryRevJButton.setText("Manage Inventory Revenue");
        ManageInventoryRevJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageInventoryRevJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(129, 129, 129)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(215, 215, 215)
                        .add(ManageInventoryJButton))
                    .add(layout.createSequentialGroup()
                        .add(215, 215, 215)
                        .add(ManageInventoryRevJButton)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jLabel1)
                .add(34, 34, 34)
                .add(ManageInventoryJButton)
                .add(34, 34, 34)
                .add(ManageInventoryRevJButton)
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageInventoryJButtonActionPerformed
        // TODO add your handling code here:
       ManageInventoryJPanel mijp=new ManageInventoryJPanel(container,publisher);
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("Manage Inventory ",mijp); 
        layout.next(container); 
    }//GEN-LAST:event_ManageInventoryJButtonActionPerformed

    private void ManageInventoryRevJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageInventoryRevJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageInventoryRevJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageInventoryJButton;
    private javax.swing.JButton ManageInventoryRevJButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
