/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductCompanyFinanceManager;

import Business.Finance.Invoice;
import Business.Finance.Payment;
import Business.Organization.FinanceOrganization;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.WorkQueue.PaymentTestWorkRequest;

/**
 *
 * @author vaibhavagarwal
 */
public class ProductCompanyPaymentDetailsJPanel extends javax.swing.JPanel {
private  JPanel container;
private  FinanceOrganization organization;
private Invoice invoice;
private Payment payment;
    /**
     * Creates new form ProductCompanyPaymentDetailsJPanel
     */
    public ProductCompanyPaymentDetailsJPanel(JPanel container,FinanceOrganization organization,Invoice invoice) {
        initComponents();
        this.container=container;
        this.organization=organization;
        this.invoice=invoice;
        payment=new Payment();
        PaymentOptionsJComboBox.removeAllItems();
     
    

  
   
        PaymentOptionsJComboBox.addItem(payment.CREDITCARD);
        PaymentOptionsJComboBox.addItem(payment.DEBITCARD);
        PaymentOptionsJComboBox.addItem(payment.TRAVELCARD);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PaymentOptionsJComboBox = new javax.swing.JComboBox();
        BankNameJtextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CardNumberJTextfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AmountJtextfield = new javax.swing.JTextField();
        PayJbutton = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();
        PinnoJTextfield = new javax.swing.JPasswordField();

        PaymentOptionsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Bank name");

        jLabel2.setText("Card number");

        jLabel3.setText("PIN No");

        jLabel4.setText("Amount ");

        PayJbutton.setText("Pay");
        PayJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayJbuttonActionPerformed(evt);
            }
        });

        backButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(PaymentOptionsJComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(34, 34, 34)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(BankNameJtextfield, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .add(CardNumberJTextfield, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .add(AmountJtextfield, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .add(PinnoJTextfield)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(68, 68, 68)
                        .add(PayJbutton)
                        .add(76, 76, 76)
                        .add(backButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(589, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(85, 85, 85)
                .add(PaymentOptionsJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(62, 62, 62)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(BankNameJtextfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(62, 62, 62)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(CardNumberJTextfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(62, 62, 62)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(PinnoJTextfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(62, 62, 62)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AmountJtextfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(PayJbutton)
                    .add(backButton4))
                .add(17, 17, 17))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 998, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 556, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PayJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayJbuttonActionPerformed
        // TODO add your handling code here:
        PaymentTestWorkRequest ptwr=new PaymentTestWorkRequest();
        //organization.getWorkQueue().getWorkRequestList().add(ptwr);
       ptwr.setSender(organization);
       ptwr.setMessage("Amount paid");
       
        
        
        String s=(String)PaymentOptionsJComboBox.getSelectedItem();
        if(s.equals(payment.CREDITCARD))
        {
            payment.setBankcreditcardinfo(BankNameJtextfield.getText());
            payment.setCcpinno(Integer.parseInt(PinnoJTextfield.getText()));
            payment.setCreditcardno(Integer.parseInt(CardNumberJTextfield.getText()));
        }

        else if(s.equals(payment.DEBITCARD))
        {
            payment.setBankdebitcardinfo(BankNameJtextfield.getText());
            payment.setDcpinno(Integer.parseInt(PinnoJTextfield.getText()));
            payment.setDebitcardno(Integer.parseInt(CardNumberJTextfield.getText()));
        }
        else
        {payment.setBanktravelcardinfo(BankNameJtextfield.getText());
            payment.setTcpinno(Integer.parseInt(PinnoJTextfield.getText()));
            payment.setTravelcardno(Integer.parseInt(CardNumberJTextfield.getText()));

        }
        int a=Integer.parseInt(AmountJtextfield.getText());
        if(a==invoice.getAmountdue())
        {   invoice.setAmountdue(0);
            invoice.setInvoicestatus("Paid");
            ptwr.setAmt(a);
        }
        else
        {
            int amountdue=invoice.getAmountdue()-a;
            invoice.setAmountdue(amountdue);
            invoice.setInvoicestatus("Partially Paid");
            ptwr.setAmt(a);
        }
    organization.getWorkQueue().getWorkRequestList().add(ptwr);
            
    }//GEN-LAST:event_PayJbuttonActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountJtextfield;
    private javax.swing.JTextField BankNameJtextfield;
    private javax.swing.JTextField CardNumberJTextfield;
    private javax.swing.JButton PayJbutton;
    private javax.swing.JComboBox PaymentOptionsJComboBox;
    private javax.swing.JPasswordField PinnoJTextfield;
    private javax.swing.JButton backButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
