/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductCompanyFinanceManager;

import Business.Finance.Invoice;
import Business.Organization.Organization;
import Business.Organization.FinanceOrganization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaibhavagarwal
 */
public class ViewInvoiceJPanel extends javax.swing.JPanel {
private  JPanel container;
 private  FinanceOrganization organization;
 
    /**
     * Creates new form ViewInvoiceJPanel
     */
    public ViewInvoiceJPanel(JPanel container,FinanceOrganization organization) {
        initComponents();
        this.container=container;
        this.organization=organization;
        poptable();
    }

    
    public void poptable()
    {
        DefaultTableModel model = (DefaultTableModel)InvoiceJtable.getModel();
        
        model.setRowCount(0);
        
        for (Invoice inv : organization.getListofinvoice()){
            Object[] row = new Object[3];
            row[0] = inv;
            row[1] = inv.getAmountdue();
            row[2]=inv.getInvoicestatus();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvoiceJtable = new javax.swing.JTable();
        RefreshJButton = new javax.swing.JButton();
        BackJbutton = new javax.swing.JButton();
        PaymentJbutton = new javax.swing.JButton();

        InvoiceJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Invoice Number", "Amount Due", "Invoice Status"
            }
        ));
        jScrollPane1.setViewportView(InvoiceJtable);

        RefreshJButton.setText("Refresh");
        RefreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshJButtonActionPerformed(evt);
            }
        });

        BackJbutton.setText("Back");
        BackJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJbuttonActionPerformed(evt);
            }
        });

        PaymentJbutton.setText("Continue to Payment");
        PaymentJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentJbuttonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(RefreshJButton)
                        .add(106, 106, 106)
                        .add(BackJbutton)
                        .add(126, 126, 126)
                        .add(PaymentJbutton)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(55, 55, 55)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 112, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(RefreshJButton)
                    .add(BackJbutton)
                    .add(PaymentJbutton))
                .add(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJbuttonActionPerformed
        // TODO add your handling code here:

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_BackJbuttonActionPerformed

    private void PaymentJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentJbuttonActionPerformed
        // TODO add your handling code here:
         int selectedrow=InvoiceJtable.getSelectedRow();
        Invoice invoice=(Invoice)InvoiceJtable.getValueAt(selectedrow,0);
        ProductCompanyPaymentDetailsJPanel pcpdjp = new ProductCompanyPaymentDetailsJPanel(container,organization,invoice);
        container.add("Payment Details", pcpdjp);

        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
        
        
        
    }//GEN-LAST:event_PaymentJbuttonActionPerformed

    private void RefreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshJButtonActionPerformed
        // TODO add your handling code here:
        poptable();
    }//GEN-LAST:event_RefreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJbutton;
    private javax.swing.JTable InvoiceJtable;
    private javax.swing.JButton PaymentJbutton;
    private javax.swing.JButton RefreshJButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
