/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdExFinance;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import javax.swing.JPanel;
import Business.Enterprise.AdExchangeEnterprise;
import java.awt.CardLayout;

/**
 *
 * @author vaibhavagarwal
 */
public class AdExFinanceMangerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel container;
    private Organization organization;
    private AdExchangeEnterprise  adex;
    /**
     * Creates new form AdExFinanceMangerWorkAreaJPanel
     */
    public AdExFinanceMangerWorkAreaJPanel(JPanel container,Organization organization,Enterprise enterprise) {
        initComponents();
        this.container=container;
        this.organization=organization;
        this.adex=(AdExchangeEnterprise)enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ViewBalanceJbutton = new javax.swing.JButton();

        jButton1.setText("Update Balance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ViewBalanceJbutton.setText("View Balance");
        ViewBalanceJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBalanceJbuttonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(209, 209, 209)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(ViewBalanceJbutton))
                .addContainerGap(525, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(81, 81, 81)
                .add(jButton1)
                .add(81, 81, 81)
                .add(ViewBalanceJbutton)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        UpdateBalanceJPanel ubjp = new UpdateBalanceJPanel(container,organization,adex);
        container.add("Update Balance JPanel", ubjp);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ViewBalanceJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBalanceJbuttonActionPerformed
        // TODO add your handling code here:
        
         ViewAdExBalanceJPanel vaejp = new ViewAdExBalanceJPanel(container,organization,adex);
        container.add("View AdExchangeBalance JPanel",vaejp);

        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_ViewBalanceJbuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewBalanceJbutton;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
