/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdExchangeBiddersManager;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Publisher;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.Enterprise.AdExchangeEnterprise;
import Business.Enterprise.ProductCompany;
import Business.Network.Network;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaibhavagarwal
 */
public class BiddersManagerJPanel extends javax.swing.JPanel {

    private JPanel container;
//private UserAccount account;
    private AdExchangeEnterprise adexchange;
    private EcoSystem system;
    int i = 0;

    /**
     *
     * /**
     * Creates new form BiddersManagerJPanel
     */
    public BiddersManagerJPanel(JPanel container, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.container = container;
        this.adexchange = (AdExchangeEnterprise) enterprise;
        this.system = system;
        //popNetworkJcombobox();
        //Network n=(Network)NetworkJcomboBox.getSelectedItem();
        popProdCompaniesCombobox();
    }

//    public void popNetworkJcombobox()
//    {  NetworkJcomboBox.removeAllItems();
//        for(Network n:system.getNetworkList())
//        {
//            NetworkJcomboBox.addItem(n);
//        }
//    }
    public void popProductCompaniestable() {
        DefaultTableModel model = (DefaultTableModel) BiddersJTable.getModel();

        model.setRowCount(0);

        for (ProductCompany p : adexchange.getProductcompanies()) {
            if (p == null) {
                continue;
            }
            Object[] row = new Object[1];
            row[0] = p.getName();
            // row[1] = organization.getName();

            model.addRow(row);
        }

    }

    public void popProdCompaniesCombobox() {
        ProductCompaniesJComboBox.removeAllItems();
        for (Network n1 : system.getNetworkList()) {
            for (Enterprise e : n1.getEnterpriseDirectory().getEnterpriseList()) /// this is to add Product Company Enterprise obejct
            {
                if (e instanceof ProductCompany) {
                    ProductCompaniesJComboBox.addItem(e);
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductCompaniesJComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        BiddersJTable = new javax.swing.JTable();
        AddJbutton = new javax.swing.JButton();
        RefreshJButton = new javax.swing.JButton();

        ProductCompaniesJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProductCompaniesJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductCompaniesJComboBoxActionPerformed(evt);
            }
        });

        BiddersJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Product Company Name"
            }
        ));
        jScrollPane1.setViewportView(BiddersJTable);

        AddJbutton.setText("Add Product Company");
        AddJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJbuttonActionPerformed(evt);
            }
        });

        RefreshJButton.setText("Refresh");
        RefreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(111, 111, 111)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(AddJbutton)
                        .add(62, 62, 62)
                        .add(RefreshJButton))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 329, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ProductCompaniesJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(41, 41, 41)
                .add(ProductCompaniesJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AddJbutton)
                    .add(RefreshJButton))
                .add(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJbuttonActionPerformed
        // TODO add your handling code here:
        Enterprise ent = (Enterprise) ProductCompaniesJComboBox.getSelectedItem();//product company variable
        // AdExchangeEnterprise adexchange=(AdExchangeEnterprise)enterprise; //it typecasts the enterprise object variable to AdExchangeEnterprise variable
        //adexchange.addProductCompany((ProductCompany)ent);
        //popProductCompaniestable();

        if (adexchange.getProductcompanies().size() > 0) {
            for (ProductCompany p1 : adexchange.getProductcompanies()) {
                if (p1 == null) {
                    adexchange.getProductcompanies().remove(p1);
                    System.out.println("p c is null");
                    continue;
                }
                ProductCompany p2 = (ProductCompany) ent;
                System.out.println("The productcompany is " + p2.getName());
                System.out.println("The productcompany in the system " + p1.getName());
                if (!p1.equals(p2)) {
                    adexchange.addProductCompany((ProductCompany) ent);
                    popProductCompaniestable();
                } else {
                    System.out.println("The productcompany " + p2.getName() + "already exists");
                    JOptionPane.showMessageDialog(null, "Advertiser already exists", "Warning", JOptionPane.YES_NO_OPTION);

                }
            }
        } else {
            adexchange.addProductCompany((ProductCompany) ent);
            popProductCompaniestable();
        }


    }//GEN-LAST:event_AddJbuttonActionPerformed

    private void RefreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshJButtonActionPerformed
        // TODO add your handling code here:
        popProductCompaniestable();
    }//GEN-LAST:event_RefreshJButtonActionPerformed

    private void ProductCompaniesJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductCompaniesJComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ProductCompaniesJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJbutton;
    private javax.swing.JTable BiddersJTable;
    private javax.swing.JComboBox ProductCompaniesJComboBox;
    private javax.swing.JButton RefreshJButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
