/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdExchangePublishersManager;

import Business.EcoSystem;
import Business.Enterprise.AdExchangeEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ProductCompany;
import Business.Enterprise.Publisher;
import Business.Network.Network;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaibhavagarwal
 */
public class PublishersManagerJPanel extends javax.swing.JPanel {
private JPanel container;
//private UserAccount account;
private AdExchangeEnterprise adexchange;
private EcoSystem system;
int i=0;
    /**
     * Creates new form PublishersManagerJPanel
     */
    public PublishersManagerJPanel(JPanel container, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.container=container;
        this.adexchange=(AdExchangeEnterprise)enterprise;
        this.system=system;
        popPublishersCombobox();
    }
    
    
    
     public void popPublisherstable()
      {
         DefaultTableModel model = (DefaultTableModel)PublishersJTable.getModel();
        
        model.setRowCount(0);
        
        for (Publisher p:adexchange.getPublishers() ){
            Object[] row = new Object[1];
            row[0] = p.getName();
           // row[1] = organization.getName();
            
            model.addRow(row);
        }
      }
     public void popPublishersCombobox()
     {
          PublishersJComboBox.removeAllItems();
           for(Network n:system.getNetworkList()) 
           {for(Enterprise e:n.getEnterpriseDirectory().getEnterpriseList()) /// this is to add Product Company Enterprise obejct
          {
            if(e instanceof Publisher)
                PublishersJComboBox.addItem(e);
          }    
      }
     }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PublishersJComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        PublishersJTable = new javax.swing.JTable();
        AddJbutton = new javax.swing.JButton();
        RefreshJButton = new javax.swing.JButton();

        PublishersJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PublishersJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Publisher Name"
            }
        ));
        jScrollPane1.setViewportView(PublishersJTable);

        AddJbutton.setText("Add Publisher");
        AddJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJbuttonActionPerformed(evt);
            }
        });

        RefreshJButton.setText("Refresh");
        RefreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(111, 111, 111)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PublishersJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(AddJbutton)
                        .add(30, 30, 30)
                        .add(RefreshJButton))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 329, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(PublishersJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(43, 43, 43)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AddJbutton)
                    .add(RefreshJButton))
                .add(75, 75, 75))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 716, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 586, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJbuttonActionPerformed
        // TODO add your handling code here:
        Enterprise ent=(Enterprise)PublishersJComboBox.getSelectedItem();//product company variable
        // AdExchangeEnterprise adexchange=(AdExchangeEnterprise)enterprise; //it typecasts the enterprise object variable to AdExchangeEnterprise variable
        for(Publisher pub :adexchange.getPublishers())
        {    Publisher p=(Publisher)ent;
            if(pub.equals(p))
         {
          JOptionPane.showMessageDialog(null, "Publisher already exists","Warning",JOptionPane.YES_NO_OPTION);
        
          i=1;
          break;
          }
        }
         
         
        if(i==0)
        {
           
        
        adexchange.addPublisher((Publisher)ent);
        popPublisherstable();
        }

    }//GEN-LAST:event_AddJbuttonActionPerformed

    private void RefreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshJButtonActionPerformed
        // TODO add your handling code here:
        popPublisherstable();;
    }//GEN-LAST:event_RefreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJbutton;
    private javax.swing.JComboBox PublishersJComboBox;
    private javax.swing.JTable PublishersJTable;
    private javax.swing.JButton RefreshJButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
