/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductCompanyProductManager;

import Business.Enterprise.ProductCompany;
import Business.Product.Product;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaibhavagarwal
 */
public class AdvertisingProductJPanel extends javax.swing.JPanel {
 private JPanel container;
//private UserAccount account;
private ProductCompany prodcomp;
    /**
     * Creates new form AdvertisingProductJPanel
     */
    public AdvertisingProductJPanel( JPanel container,ProductCompany prodcomp)
    {
//private UserAccount account;
      initComponents();
      this.container=container;
      this.prodcomp=prodcomp;
     popproductstable();
    }

    
    public void popproductstable()
    {
        DefaultTableModel model = (DefaultTableModel)ProductsJTable.getModel();
        
        model.setRowCount(0);
        
        for (Product p : prodcomp.getProddir().getProductlist()){
            Object[] row = new Object[4];
            row[0] = p;
            row[1] = p.getCategory();
            row[2] = p.getPrice();
            row[3] = p.getPhoto();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProductsJTable = new javax.swing.JTable();
        SaveJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        ProductsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Category", "Price", "PhotoPath"
            }
        ));
        jScrollPane1.setViewportView(ProductsJTable);
        ProductsJTable.getColumnModel().getColumn(1).setResizable(false);
        ProductsJTable.getColumnModel().getColumn(2).setResizable(false);
        ProductsJTable.getColumnModel().getColumn(3).setResizable(false);

        SaveJButton.setText("Save");
        SaveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(68, 68, 68)
                .add(SaveJButton)
                .add(186, 186, 186)
                .add(backJButton)
                .addContainerGap(651, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(48, 48, 48)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(SaveJButton)
                    .add(backJButton))
                .add(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void SaveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveJButtonActionPerformed
        // TODO add your handling code here:
        int rowselected=ProductsJTable.getSelectedRow();
        Product p=(Product)ProductsJTable.getValueAt(rowselected, 0);
        prodcomp.setAdvertisedproduct(p);
    }//GEN-LAST:event_SaveJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductsJTable;
    private javax.swing.JButton SaveJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
