/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductCompanyProductManager;

import Business.Enterprise.Enterprise;
import Business.Enterprise.ProductCompany;
import Business.Product.Product;
import Business.Product.Product.ProductType;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vaibhavagarwal
 */
public class CreateProductJPanel extends javax.swing.JPanel {
 private JPanel container;
//private UserAccount account;
private ProductCompany prodcomp;
private JFileChooser Jfilechooser;
private Product p;
    /**
     * Creates new form CreateProductJPanel
     */
    public CreateProductJPanel(JPanel container,Enterprise enterprise) {
        initComponents();
        this.container=container;
        this.prodcomp=(ProductCompany)enterprise;
        populateCombo();
    }
    
    
      private void populateCombo(){
       PorductCategoryJCombobox.removeAllItems();
        for (ProductType type : Product.ProductType.values()){
            //System.out.println(type);
            //if (!type.getValue().equals(Type.Admin.getValue()))
                PorductCategoryJCombobox.addItem(type);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ProdNameJTextfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ProdCategoryJTextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ProductPriceJTextfied = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        UploadImageJButton = new javax.swing.JButton();
        PorductCategoryJCombobox = new javax.swing.JComboBox();

        AddJButton.setText("Add");
        AddJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Product Name");

        jLabel2.setText("Product Category");

        jLabel3.setText("Product Price");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Product Image");

        UploadImageJButton.setText("Upload Image");
        UploadImageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadImageJButtonActionPerformed(evt);
            }
        });

        PorductCategoryJCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(101, 101, 101)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(AddJButton)
                        .add(7, 7, 7)
                        .add(backJButton))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel4)
                            .add(jLabel1))
                        .add(79, 79, 79)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ProductPriceJTextfied)
                            .add(UploadImageJButton)
                            .add(ProdNameJTextfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(ProdCategoryJTextfield)
                                .add(62, 62, 62)
                                .add(PorductCategoryJCombobox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jLabel2))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {ProdCategoryJTextfield, ProdNameJTextfield, ProductPriceJTextfied}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(ProdCategoryJTextfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(PorductCategoryJCombobox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ProdNameJTextfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(40, 40, 40)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(ProductPriceJTextfied, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(39, 39, 39)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(UploadImageJButton))
                        .add(56, 56, 56)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AddJButton)
                    .add(backJButton))
                .add(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void AddJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJButtonActionPerformed
        // TODO add your handling code here:
       ProductType type=(ProductType)PorductCategoryJCombobox.getSelectedItem();
       this.p.setCategory(type.getValue());
       this.p.setName(ProdNameJTextfield.getText());
       this.p.setPrice(Integer.parseInt(ProductPriceJTextfied.getText()));
        
    }//GEN-LAST:event_AddJButtonActionPerformed

    private void UploadImageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadImageJButtonActionPerformed
        // TODO add your handling code here:
         Jfilechooser=new JFileChooser();
         Jfilechooser.showOpenDialog(null);
          File f=Jfilechooser.getSelectedFile(); // choosing the selected file
          String filename=f.getAbsolutePath();   //storing the absolute path of the file in a string
          System.out.println(f.getAbsolutePath());
          if(f!=null)
          {
           this.p=prodcomp.getProddir().createandaddProduct();
           this.p.setPhoto(filename);  
          }//setting the path of file in one of the attributes of driver class
          else
          {
            JOptionPane.showConfirmDialog(null,"Upload failed.Upload photo again", "Warning", JOptionPane.YES_NO_OPTION);
          }
                   
    }//GEN-LAST:event_UploadImageJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJButton;
    private javax.swing.JComboBox PorductCategoryJCombobox;
    private javax.swing.JTextField ProdCategoryJTextfield;
    private javax.swing.JTextField ProdNameJTextfield;
    private javax.swing.JTextField ProductPriceJTextfied;
    private javax.swing.JButton UploadImageJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
