/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductCompanyProductManager;

import Business.EcoSystem;
import Business.Enterprise.AdExchangeEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ProductCompany;
import Business.Product.Product;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaibhavagarwal
 */
public class ManageProductsJPanel extends javax.swing.JPanel {
    private JPanel container;
//private UserAccount account;
private ProductCompany prodcomp;
private EcoSystem system;

    /**
     * Creates new form ManageProductsJPanel
     */
    public ManageProductsJPanel(JPanel container,Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.container=container;
        this.prodcomp=(ProductCompany)enterprise;
        this.system=system;
        popproductstable();
    }

    
    public void popproductstable()
    {
        DefaultTableModel model = (DefaultTableModel)ProductsJTable.getModel();
        
        model.setRowCount(0);
        
        for (Product p : prodcomp.getProddir().getProductlist()){
            Object[] row = new Object[3];
            row[0] = p;
            row[1] = p.getCategory();
            row[2] = p.getPrice();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProductsJTable = new javax.swing.JTable();
        ViewProductsJbutton = new javax.swing.JButton();
        CreateProductJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        DeleteJbutton = new javax.swing.JButton();

        ProductsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Category", "Price"
            }
        ));
        jScrollPane1.setViewportView(ProductsJTable);

        ViewProductsJbutton.setText("View Products");
        ViewProductsJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductsJbuttonActionPerformed(evt);
            }
        });

        CreateProductJButton.setText("Create Product");
        CreateProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateProductJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        DeleteJbutton.setText("Delete");
        DeleteJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteJbuttonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(81, 81, 81)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(94, 94, 94)
                        .add(ViewProductsJbutton)
                        .add(50, 50, 50)
                        .add(CreateProductJButton)
                        .add(44, 44, 44)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(DeleteJbutton)
                            .add(backJButton))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 47, Short.MAX_VALUE)
                .add(DeleteJbutton)
                .add(38, 38, 38)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(CreateProductJButton)
                    .add(ViewProductsJbutton)
                    .add(backJButton))
                .add(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void CreateProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateProductJButtonActionPerformed
        // TODO add your handling code here:
         CreateProductJPanel cpjp=new CreateProductJPanel(container, prodcomp);
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("Create Product JPanel",cpjp); 
        layout.next(container);
    }//GEN-LAST:event_CreateProductJButtonActionPerformed

    private void ViewProductsJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductsJbuttonActionPerformed
        // TODO add your handling code here:
        popproductstable();
    }//GEN-LAST:event_ViewProductsJbuttonActionPerformed

    private void DeleteJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteJbuttonActionPerformed
        // TODO add your handling code here:
        int selectedrow=ProductsJTable.getSelectedRow();

        if (selectedrow>=0)
        {Product  product=(Product)ProductsJTable.getValueAt(selectedrow, 0);

            ArrayList<Product> prodlist=prodcomp.getProddir().getProductlist();
            // remove person object from array
            //you van remove it by index if you want

            prodlist.remove(product);

        }

        else {
            JOptionPane.showConfirmDialog(null,"select one row please", "Warning", JOptionPane.YES_NO_OPTION);

        }
    }//GEN-LAST:event_DeleteJbuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateProductJButton;
    private javax.swing.JButton DeleteJbutton;
    private javax.swing.JTable ProductsJTable;
    private javax.swing.JButton ViewProductsJbutton;
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
