/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductCompanyProductManager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ProductCompany;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vaibhavagarwal
 */
public class ProductManagerWorkAreaJPanel extends javax.swing.JPanel {
 private JPanel container;
//private UserAccount account;
private ProductCompany prodcomp;
private EcoSystem system;

    /**
     * Creates new form ProductManagerWorkAreaJPanel
     */
    public ProductManagerWorkAreaJPanel(JPanel container,Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.container=container;
        this.prodcomp=(ProductCompany)enterprise;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageProductsJButton = new javax.swing.JButton();
        AdvertisingProductJButton = new javax.swing.JButton();

        ManageProductsJButton.setText("Manage Products");
        ManageProductsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProductsJButtonActionPerformed(evt);
            }
        });

        AdvertisingProductJButton.setText("Advertising Product");
        AdvertisingProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvertisingProductJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(181, 181, 181)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(AdvertisingProductJButton)
                    .add(ManageProductsJButton))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(67, 67, 67)
                .add(ManageProductsJButton)
                .add(46, 46, 46)
                .add(AdvertisingProductJButton)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageProductsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProductsJButtonActionPerformed
        // TODO add your handling code here:
        ManageProductsJPanel mpjp=new ManageProductsJPanel(container, prodcomp, system);
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("RequestLabTestJPanel",mpjp); 
        layout.next(container);
    }//GEN-LAST:event_ManageProductsJButtonActionPerformed

    private void AdvertisingProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvertisingProductJButtonActionPerformed
        // TODO add your handling code here:
        AdvertisingProductJPanel apjp=new AdvertisingProductJPanel(container, prodcomp);
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("RequestLabTestJPanel",apjp); 
        layout.next(container);
    }//GEN-LAST:event_AdvertisingProductJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdvertisingProductJButton;
    private javax.swing.JButton ManageProductsJButton;
    // End of variables declaration//GEN-END:variables
}
